# fly.toml file generated for float on 2021-12-24T20:49:33-05:00

app = "float"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[build]
dockerfile = "Dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2222
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 100
    soft_limit = 50
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 5000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
